#!/usr/bin/env python3
"""Extract Hyprland's Lua config API surface from its source tree.

Reads the Hyprland source the flake actually ships and emits a Lua module
describing every name the config runtime registers: hl.* functions, the
hl.dsp dispatcher tree, valid hl.on event names, and the monitor object's
readable fields. The hyprland-lua-runtime check feeds this to a strict mock,
so omarchy config code that touches API absent from the shipped compositor
fails here instead of on a user's first monitor event.

Usage: extract-surface.py <hyprland-src> <output.lua>
"""

import re
import sys
from pathlib import Path

LUA_DIR = "src/config/lua"


def fail(message: str) -> None:
    print(f"extract-surface: {message}", file=sys.stderr)
    print(
        "extract-surface: Hyprland's Lua config sources moved or changed shape; "
        "update tests/hyprland-lua-runtime/extract-surface.py for the pinned "
        "Hyprland before trusting this check again.",
        file=sys.stderr,
    )
    sys.exit(1)


def read(src: Path, relative: str) -> str:
    path = src / relative
    if not path.is_file():
        fail(f"missing {relative}")
    return path.read_text(encoding="utf-8", errors="replace")


def extract_flat_functions(src: Path) -> list[str]:
    """hl.* function names from every bindings file except the dispatcher
    tree, which registers its names inside nested tables."""
    names: set[str] = set()
    bindings = src / LUA_DIR / "bindings"
    if not bindings.is_dir():
        fail(f"missing {LUA_DIR}/bindings")
    for path in sorted(bindings.glob("*.cpp")):
        if path.name == "LuaBindingsDispatchers.cpp":
            continue
        for match in re.finditer(
            r'set(?:Mgr)?Fn\(L,(?:\s*mgr,)?\s*"([a-z_0-9]+)"', path.read_text()
        ):
            names.add(match.group(1))
    if "get_active_monitor" not in names or "workspace_rule" not in names:
        fail("flat function extraction lost core names; parser needs updating")
    return sorted(names)


def extract_dsp_tree(src: Path) -> dict[str, list[str]]:
    """The hl.dsp namespace: {"" : top-level fns, group-name: fns}."""
    text = read(src, f"{LUA_DIR}/bindings/LuaBindingsDispatchers.cpp")
    end = text.find('lua_setfield(L, -2, "dsp")')
    if end == -1:
        fail("no hl.dsp registration found")
    fn_start = text.rfind("void ", 0, end)
    block = text[fn_start:end]

    groups: dict[str, list[str]] = {}
    current: list[str] = []
    toplevel: list[str] = []
    pattern = re.compile(
        r'setFn\(L,\s*"([a-z_0-9]+)"|lua_setfield\(L,\s*-2,\s*"([a-z_0-9]+)"\)|lua_newtable\(L\)'
    )
    for match in pattern.finditer(block):
        fn, close = match.group(1), match.group(2)
        if match.group(0) == "lua_newtable(L)":
            toplevel.extend(current)
            current = []
        elif fn:
            current.append(fn)
        elif close:
            groups[close] = current
            current = []
    toplevel.extend(current)
    groups[""] = toplevel
    if "exec_cmd" not in toplevel or "window" not in groups:
        fail("dsp tree extraction lost core names; parser needs updating")
    return groups


def extract_events(src: Path) -> list[str]:
    text = read(src, f"{LUA_DIR}/LuaEventHandler.cpp")
    events = sorted(set(re.findall(r'"([a-z_]+(?:\.[a-z_]+)+)"', text)))
    if "monitor.focused" not in events:
        fail("event extraction lost monitor.focused; parser needs updating")
    return events


def extract_monitor_fields(src: Path) -> list[str]:
    text = read(src, f"{LUA_DIR}/objects/LuaMonitor.cpp")
    fields = sorted(set(re.findall(r'key == "([a-z_]+)"', text)))
    if "scale" not in fields:
        fail("monitor field extraction lost scale; parser needs updating")
    return fields


def lua_list(items) -> str:
    return "{ " + ", ".join(f'"{item}"' for item in items) + " }"


def main() -> None:
    if len(sys.argv) != 3:
        fail("usage: extract-surface.py <hyprland-src> <output.lua>")
    src = Path(sys.argv[1])

    flat = extract_flat_functions(src)
    dsp = extract_dsp_tree(src)
    events = extract_events(src)
    monitor_fields = extract_monitor_fields(src)

    lines = ["-- Generated by extract-surface.py; do not edit.", "return {"]
    lines.append(f"  fns = {lua_list(flat)},")
    lines.append("  dsp = {")
    lines.append(f"    [\"\"] = {lua_list(dsp.pop(''))},")
    for group, fns in sorted(dsp.items()):
        lines.append(f"    {group} = {lua_list(fns)},")
    lines.append("  },")
    lines.append(f"  events = {lua_list(events)},")
    lines.append(f"  monitor_fields = {lua_list(monitor_fields)},")
    lines.append("}")

    Path(sys.argv[2]).write_text("\n".join(lines) + "\n")
    print(
        f"surface: {len(flat)} fns, {sum(len(v) for v in dsp.values())} dsp names "
        f"in {len(dsp)} groups, {len(events)} events, "
        f"{len(monitor_fields)} monitor fields"
    )


if __name__ == "__main__":
    main()
